function save_dummy_fixtures()
%SAVE_DUMMY_FIXTURES Write dummy_locs.mat and dummy_locs.csv to this
% folder, generated by makeDummyLineLocs. Re-run after changing the
% generator to refresh the on-disk fixtures.

fixtures_dir = fileparts(mfilename('fullpath'));
locs = makeDummyLineLocs();

saveloc.loc = locs; %#ok<STRNU>
fileformat = 'sml'; %#ok<NASGU>
save(fullfile(fixtures_dir, 'dummy_locs.mat'), 'saveloc', 'fileformat');

% raw single-channel CSV layout matching config/csv_KG_gaussfit.txt
csv_table = table(locs.frame, double(locs.phot), double(locs.bg), ...
    double(locs.xnm), double(locs.ynm), double(locs.PSFxnm), double(locs.PSFynm), ...
    'VariableNames', {'frame', 'photons', 'background', 'xnm', 'ynm', 'PSFxnm', 'PSFynm'});
writetable(csv_table, fullfile(fixtures_dir, 'dummy_locs.csv'));

end
